#!/bin/sh
set -eu

cd /~arcowo || exit # better go to hardcoded home because of 'sudo HOME-disallowed -rm' will use /root

allowed_read=$0.allowlist

from_stdin=0
case $# in
	0) r=cat; [ -t 1 ] && r=ll;;
	*)
		case $1 in
			-) from_stdin=1; r=${2:?"use --help for usage"}; shift 2;;
			*) r=$1; shift;;
		esac
	;;
esac

bars=1
case ${from_stdin:-x}:$r in
	1:*|?:cat) bars=0
esac


case $r in
	help|--help)
		printf %s\\n \
			"Usage:   ${0##*/} [-] [ll|ls|rm|rm-f|cat] [...args]" \
			"         ${0##*/} edit" \
			"" \
			"Commands:" \
			"  -          read from stdin files to rm/ls from homedir" \
			"  ll|ls      calls '\$1 \$@ -- DISALLOWED_FILES', the default when no args" \
			"  rm         calls 'rm \${@:-\"-riv\"} -- DISALLOWED_FILES'" \
			"  rm-f       calls 'rm -rfv \$@ -- DISALLOWED_FILES'" \
			"  cat        just prints not allowed files" \
			"  edit       edit allowlist" \
			"  [--]help   prints usage and exit" \
			"" \
			"   Print/remove not allowed files in your homedir" \
			"   And print curent staus of directoryes + files" \
		;
		exit
	;;
	edit) set -f; exec ${EDITOR:-vi} "$@" "$allowed_read"; exit;;
esac

[ -f "$allowed_read" ] || {
	printf %s\\n "${0##*/}: File to read allowed files list does not exist, use '${0##*/} edit' and save to csreate it"
	exit 1
}


printf_existing_files() { if [ -e "$1" ]; then printf %s\\n "$@"; fi; }


[ "$bars" -eq 1 ] && { pwd; echo; } >&2


case $from_stdin in
	1) cat;;
	0)
		{
			printf_existing_files .[!.]*
			printf_existing_files *
		} | {
			grep -vxFf "$allowed_read"
		}
	;;
esac | case $r in
	cat) cat;;
	ll|ls) xargs    -d \\n -r "${r##*","}" -d "$@" --;;
	rm)    xargs -o -d \\n -r rm "${@:-"-riv"}" --;;
	rm-f)  xargs -o -d \\n -r rm -rfv "$@" --;;
	*) echo 'use --help for usage' >&2; exit 2;;
esac


[ "$bars" -eq 1 ] || exit 0

len_existing() { if [ -e "$1" ]; then echo $#; else echo 0; fi; }

total=$(( $(len_existing * ) + $(len_existing .[!.]* ) ))
dirs=$((  $(len_existing */) + $(len_existing .[!.]*/) ))
printf >&2 %s\\n '' "$dirs dirs + $(( total - dirs )) files = $total"
